# Generated by Django 3.1.2 on 2020-11-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopicRelationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('insertedAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('topicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.topic')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.user')),
            ],
            options={
                'unique_together': {('userId', 'topicId')},
            },
        ),
    ]
