# Generated by Django 3.1.2 on 2020-11-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventDescription',
            field=models.CharField(default='', max_length=100),
        ),
    ]
