# Generated by Django 3.1.2 on 2020-11-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_event_eventdescription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usereventrelationship',
            unique_together={('userId', 'eventId')},
        ),
    ]
