# Generated by Django 3.1.2 on 2020-11-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0003_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topicName',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
