# Generated by Django 3.1.2 on 2020-11-20 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0004_auto_20201119_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=50, unique=True)),
                ('eventType', models.CharField(max_length=30)),
                ('eventDate', models.DateTimeField(auto_now=True)),
                ('eventDuration', models.CharField(max_length=20)),
                ('eventHost', models.CharField(max_length=30)),
                ('eventLocation', models.CharField(max_length=30)),
                ('insertedAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEventRelationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('insertedAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.event')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
